import { AnalyzeResponse } from "./analyze-api";

interface BuildGithubIssueUrlParams {
  repositoryUrl: string;
  analysis: AnalyzeResponse;
  reportedError?: string;
}

interface GithubRepositoryCoordinates {
  owner: string;
  repository: string;
}

const MAX_ISSUE_TITLE_LENGTH = 90;
const MAX_REPORTED_ERROR_LENGTH = 1200;

export function buildGithubIssueUrl(
  params: BuildGithubIssueUrlParams,
): string | null {
  const repository = parseGithubRepositoryUrl(params.repositoryUrl);
  if (!repository) {
    return null;
  }

  const issueUrl = new URL(
    `https://github.com/${repository.owner}/${repository.repository}/issues/new`,
  );

  issueUrl.searchParams.set("title", buildIssueTitle(params.analysis));
  issueUrl.searchParams.set(
    "body",
    buildIssueBody(params.analysis, params.repositoryUrl, params.reportedError),
  );

  return issueUrl.toString();
}

function parseGithubRepositoryUrl(
  repositoryUrl: string,
): GithubRepositoryCoordinates | null {
  try {
    const parsed = new URL(repositoryUrl);
    if (parsed.hostname !== "github.com") {
      return null;
    }

    const pathSegments = parsed.pathname
      .split("/")
      .filter((segment) => segment.length > 0);

    if (pathSegments.length < 2) {
      return null;
    }

    const owner = pathSegments[0];
    const rawRepository = pathSegments[1];
    const repository = rawRepository.endsWith(".git")
      ? rawRepository.slice(0, -4)
      : rawRepository;

    if (!owner || !repository) {
      return null;
    }

    return { owner, repository };
  } catch {
    return null;
  }
}

function buildIssueTitle(analysis: AnalyzeResponse): string {
  const normalizedProblem = analysis.problem.replace(/\s+/g, " ").trim();
  const title = `[${analysis.priority}] ${normalizedProblem}`;

  if (title.length <= MAX_ISSUE_TITLE_LENGTH) {
    return title;
  }

  return `${title.slice(0, MAX_ISSUE_TITLE_LENGTH - 3).trimEnd()}...`;
}

function buildIssueBody(
  analysis: AnalyzeResponse,
  repositoryUrl: string,
  reportedError?: string,
): string {
  return [
    "## Problema",
    analysis.problem,
    "",
    "## Causa",
    analysis.cause,
    "",
    "## Problematica que genera",
    analysis.impact,
    "",
    "## Prioridad",
    `\`${analysis.priority}\``,
    "",
    "## Solucion sugerida",
    analysis.solution,
    "",
    "## Error log",
    formatReportedError(reportedError),
    "",
    "## Metadata",
    `- Repository: ${repositoryUrl}`,
    `- Generated by: Dev Decision Engine`,
    `- Generated at: ${new Date().toISOString()}`,
  ].join("\n");
}

function formatReportedError(reportedError?: string): string {
  if (!reportedError || reportedError.trim().length === 0) {
    return "_No stacktrace provided._";
  }

  const normalizedError = reportedError.trim();
  if (normalizedError.length <= MAX_REPORTED_ERROR_LENGTH) {
    return toCodeBlock(normalizedError);
  }

  const truncatedError = normalizedError
    .slice(0, MAX_REPORTED_ERROR_LENGTH)
    .trimEnd();

  return `${toCodeBlock(truncatedError)}\n\n_Truncated to ${MAX_REPORTED_ERROR_LENGTH} chars._`;
}

function toCodeBlock(content: string): string {
  return ["```text", content, "```"].join("\n");
}
