import { AnalyzeFinding, AnalyzeResponse } from "./analyze-api";

interface BuildGithubIssueUrlsParams {
  repositoryUrl: string;
  analysis: AnalyzeResponse;
  reportedError?: string;
}

interface GithubRepositoryCoordinates {
  owner: string;
  repository: string;
}

export interface GithubIssueDraft {
  findingIndex: number;
  finding: AnalyzeFinding;
  url: string;
}

const MAX_ISSUE_TITLE_LENGTH = 90;
const MAX_REPORTED_ERROR_LENGTH = 1200;

export function buildGithubIssueUrls(
  params: BuildGithubIssueUrlsParams,
): GithubIssueDraft[] {
  const repository = parseGithubRepositoryUrl(params.repositoryUrl);
  if (!repository) {
    return [];
  }

  return params.analysis.findings.map((finding, index) => {
    const issueUrl = new URL(
      `https://github.com/${repository.owner}/${repository.repository}/issues/new`,
    );

    issueUrl.searchParams.set("title", buildIssueTitle(finding));
    issueUrl.searchParams.set(
      "body",
      buildIssueBody({
        analysis: params.analysis,
        finding,
        findingIndex: index,
        repositoryUrl: params.repositoryUrl,
        reportedError: params.reportedError,
      }),
    );

    return {
      findingIndex: index,
      finding,
      url: issueUrl.toString(),
    };
  });
}

function parseGithubRepositoryUrl(
  repositoryUrl: string,
): GithubRepositoryCoordinates | null {
  try {
    const parsed = new URL(repositoryUrl);
    if (parsed.hostname !== "github.com") {
      return null;
    }

    const pathSegments = parsed.pathname
      .split("/")
      .filter((segment) => segment.length > 0);

    if (pathSegments.length < 2) {
      return null;
    }

    const owner = pathSegments[0];
    const rawRepository = pathSegments[1];
    const repository = rawRepository.endsWith(".git")
      ? rawRepository.slice(0, -4)
      : rawRepository;

    if (!owner || !repository) {
      return null;
    }

    return { owner, repository };
  } catch {
    return null;
  }
}

function buildIssueTitle(finding: AnalyzeFinding): string {
  const normalizedProblem = finding.problem.replace(/\s+/g, " ").trim();
  const title = `[${finding.priority}] ${normalizedProblem}`;

  if (title.length <= MAX_ISSUE_TITLE_LENGTH) {
    return title;
  }

  return `${title.slice(0, MAX_ISSUE_TITLE_LENGTH - 3).trimEnd()}...`;
}

function buildIssueBody({
  analysis,
  finding,
  findingIndex,
  repositoryUrl,
  reportedError,
}: {
  analysis: AnalyzeResponse;
  finding: AnalyzeFinding;
  findingIndex: number;
  repositoryUrl: string;
  reportedError?: string;
}): string {
  return [
    "## Resumen del análisis",
    analysis.summary,
    "",
    "## Problema",
    finding.problem,
    "",
    "## Causa",
    finding.cause,
    "",
    "## Impacto",
    finding.impact,
    "",
    "## Prioridad",
    `\`${finding.priority}\``,
    "",
    "## Solución sugerida",
    finding.solution,
    "",
    "## Próxima acción sugerida",
    finding.nextAction,
    "",
    "## Confianza",
    `${finding.confidence}%`,
    "",
    "## Contexto del análisis",
    `- Hallazgo: ${findingIndex + 1} de ${analysis.findings.length}`,
    `- Modo: ${analysis.mode}`,
    "",
    "## Error log",
    formatReportedError(reportedError),
    "",
    "## Metadata",
    `- Repository: ${repositoryUrl}`,
    `- Generated by: Dev Decision Engine`,
    `- Generated at: ${new Date().toISOString()}`,
  ].join("\n");
}

function formatReportedError(reportedError?: string): string {
  if (!reportedError || reportedError.trim().length === 0) {
    return "_No stacktrace provided._";
  }

  const normalizedError = reportedError.trim();
  if (normalizedError.length <= MAX_REPORTED_ERROR_LENGTH) {
    return toCodeBlock(normalizedError);
  }

  const truncatedError = normalizedError
    .slice(0, MAX_REPORTED_ERROR_LENGTH)
    .trimEnd();

  return `${toCodeBlock(truncatedError)}\n\n_Truncated to ${MAX_REPORTED_ERROR_LENGTH} chars._`;
}

function toCodeBlock(content: string): string {
  return ["```text", content, "```"].join("\n");
}
